const fs = require('fs');
// Configure Angular `environment.ts` file path
const targetPath = './src/environments/environment.ts';
// Load node modules
const colors = require('colors');
require('dotenv').config();
// `environment.ts` file structure
const envConfigFile = `
// This file is auto-generated by 'set-env.ts'.  Adjust any new variables there or configure variables with a .env file.

export const environment = {
	production: ${process.env.PRODUCTION || false}
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as 'zone.run', 'zoneDelegate.invokeTask'.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
`;
console.log(colors.magenta('The file `environment.ts` will be written with the following content: \n'));
console.log(colors.grey(envConfigFile));
fs.writeFile(targetPath, envConfigFile, function(err) {
	if (err) {
		throw console.error(err);
	} else {
		console.log(colors.magenta(`Angular environment.ts file generated correctly at ${targetPath} \n`));
		process.exit();
	}
});
